# Site settings.

# Without a clear rule enforced, both title and name are used.
title: XCDL / xPack
name: XCDL / xPack
description: The eXtensible Component Definition Language component framework

email: il@livius.net

destination: _site
exclude:
  - README.md
  - jekyll-serve.command
  - jekyll-build.command
  - atom.command
  - localhost-4000.webloc

# Used in sitemap.xml.
url: "http://ilg-ul.github.io" # the base hostname & protocol for your site.

# The subpath of your site, e.g. /blog (note the leading slash and the
# absence of a trailing slash).
baseurl: ""

# This timezone is used to display post dates and last modified messages.
timezone: UTC

encoding: utf-8

# Default permalink used for posts.
permalink: /blog/:year/:month/:day/:title/

# Build settings.
markdown: kramdown
# markdown: redcarpet

kramdown:
  input: GFM

redcarpet:
  extensions:
    - no_intra_emphasis
    - tables
    - fenced_code_blocks
    - autolink
    - strikethrough
    - superscript
    - highlight
    - with_toc_data
    - safe_links_only

# Warning: paginator retired in Jekyll 3!
# Make this larger, probably 5 is a good choice.
# paginate: 2
# paginate_path: "/blog/page:num/"

# The number of links added to the 'Latest news' box.
latest-news-pages: 4

# Currently disabled, since it generates incomplete content.
# Use manually written RSS feed.xml.
#   - jekyll-feed
# {% feed_meta %} in head.html

# jekyll-last-modified-at is not available on GitHub Pages.
gems:
  - jekyll-last-modified-at
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap

# Custom definitions.

# References to the project associated with the web.
github-username:  ilg-ul
github-project-name: xcdl/xcdl-go
github-project-url: http://github.com/xcdl/xcdl-go

# Change it to refer to project's page
# facebook-url: https://facebook.com/ilg-ul/

# twitter-url: http://twitter.com/ilegeul

# If you have one, define it here.
google-analytics-id: UA-16767008-13

# Disable it if no site footer is needed.
# custom-footer-content: content/site-custom-footer.markdown

# jekyll-toc-generator
tocTopTag: h2
minItemsToShowToc: 3
useExistingAnchors: true

css-date: 201510121951

# Content copyright. Update it to your needs.
copyright-message: "© 2015 Liviu Ionescu"
